# Build and publish image to GitHub (ghcr.io)
name: Publish Docker Image
on:
  push:
    branches:
      - main
      # TODO - only if has a release tag
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      
      - name: Build and push
        run: |
          docker build . --file Dockerfile --tag ghcr.io/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository }}:latest

