name: Publish docker image
on:
  pull_request:
    branches:
      - main
      # TODO - only if has a release tag
jobs:
  push-to-container-registry:
    if: github.repository == 'RMCrean/gh_actions_hugo_testing' 
    name: Build and push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
    
    # Cancel earlier job if there is a new one for the same branch/release
    concurrency:
      group: ${{ github.ref }}-docker-build
      cancel-in-progress: true
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Convert repository name to lowercase
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | awk '{print tolower($0)}')" >> $GITHUB_ENV
            
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        run: |
          docker build . --file Dockerfile --tag ghcr.io/${{ env.REPO_NAME }}:latest
          docker push ghcr.io/${{ env.REPO_NAME }}:latest


