name: HTMLChecker
on: [push, pull_request]

jobs:
  html_checker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: '0.119.0'
      
    - name: Build Hugo
      run: hugo --minify

    - name: HTML Test
      continue-on-error: true
      run: |
        curl https://htmltest.wjdp.uk | bash
        bin/htmltest 

    - name: Archive htmltest results
      uses: actions/upload-artifact@v3
      with:
        name: htmltest-report
        path: tmp/.htmltest/htmltest.log
        retention-days: 7