name: Lighthouse
on: [push]
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.119.0'
        
      - name: Build Hugo
        run: hugo --minify

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v11
        env:
          LHCI_GITHUB_TOKEN: ${{ secrets.LHCI_GITHUB_TOKEN }}
        with:
          configPath: ${{ github.workspace }}/.github/lighthouserc.json
          temporaryPublicStorage: true

