name: Markdownlint
on: [push]

jobs:
  Markdownlint:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            content
            ".github"
      

      - name: list files 
        run: ls -la 

      - name: list files in github folder
        run: ls -la .github

      - name: Run Markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          config: ".github/.markdownlint-cli2.yaml" 
          globs: "content/**/*.md"
          fix: true
          