name: Markdownlint
on: [push, pull_request]

jobs:
  Markdownlint:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            sparse-checkout: |
                content
                .github/markdownlintconfig.yml

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install markdownlint
        run: npm install -g markdownlint-cli
            
      - name: Run Markdownlint
        run: markdownlint ${GITHUB_WORKSPACE}/content/ -c ${GITHUB_WORKSPACE}/.github/markdownlintconfig.yml