name: Markdownlint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - fakebranch

jobs:
  Markdownlint:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            content
            .github/.markdownlint-cli2.jsonc

      - name: Run Markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          config: ".github/.markdownlint-cli2.jsonc" 
          globs: "content/"
          